#!/usr/bin/env python3
"""Build the deterministic catalog of tracked planning artifacts."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLANS = ROOT / "docs/plans"
OUTPUT = PLANS / "artifact-catalog.md"
ARTIFACT_DIRS = (
    ("PRDs", "prd"),
    ("Features", "feature"),
    ("Specs", "spec"),
    ("Runs", "run"),
    ("Evaluations And Schema Audits", "evaluation"),
    ("Fix Logs", "fix"),
    ("Heuristic Backlogs", "heuristic"),
)


class CatalogError(RuntimeError):
    pass


def metadata(document: str, label: str) -> str:
    match = re.search(rf"^- {re.escape(label)}:\s*(.+)$", document, re.MULTILINE)
    if not match:
        return "—"
    value = match.group(1).strip()
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    return value.replace("|", "\\|")


def artifact_row(path: Path, plans: Path = PLANS) -> str:
    document = path.read_text(encoding="utf-8")
    title_match = re.search(r"^#\s+(.+)$", document, re.MULTILINE)
    if not title_match:
        try:
            display_path = path.relative_to(ROOT)
        except ValueError:
            display_path = path
        raise CatalogError(f"{display_path} has no H1 title")
    title = title_match.group(1).strip().replace("|", "\\|")
    status = metadata(document, "Status")
    relation = "—"
    for label in ("Feature", "Parent Feature", "Parent PRD", "Run ID"):
        relation = metadata(document, label)
        if relation != "—":
            break
    return f"| [{title}]({path.relative_to(plans).as_posix()}) | {status} | {relation} |"


def render(root: Path = ROOT) -> str:
    plans = root / "docs/plans"
    lines = [
        "# Planning Artifact Catalog",
        "",
        "This generated index makes every tracked planning and execution artifact reachable without turning the current-state Plans Index into a historical registry.",
        "",
        "Edit the owning artifact, then run `uv run python scripts/build-plan-artifact-catalog.py build`. Do not edit this file directly.",
        "",
        "Status and relation values are preserved from each owner artifact. `—` means the field is not declared or does not apply; historical Spec `passed` and Run `complete` values are legacy aliases preserved under [Execution Artifact Status](../policies/harness/execution-loop-governance.md#execution-artifact-status).",
        "",
    ]
    for heading, directory in ARTIFACT_DIRS:
        paths = sorted(
            path
            for path in (plans / directory).glob("*.md")
            if not path.name.startswith("template-")
        )
        lines.extend(
            [
                f"## {heading} ({len(paths)})",
                "",
                "| Artifact | Status | Parent Or Run |",
                "| --- | --- | --- |",
            ]
        )
        lines.extend(artifact_row(path, plans) for path in paths)
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("build", "check"))
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    try:
        expected = render()
        if args.mode == "build":
            args.output.write_text(expected, encoding="utf-8")
            print(f"Built plan artifact catalog: {args.output}")
        elif not args.output.exists():
            raise CatalogError(f"Missing plan artifact catalog: {args.output}")
        elif args.output.read_text(encoding="utf-8") != expected:
            raise CatalogError("Plan artifact catalog is stale")
        else:
            print("Plan artifact catalog is current.")
    except (CatalogError, OSError) as error:
        print(error)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
